defaults:
  - _self_
  - dataset: urbansound
  - model: lstm

dataloader:
    pin_memory: False
    num_workers: 1
    batch_size: 32

optimizer:
    lr: 0.001

trainer:
    max_epochs: 10
    log_every_n_steps: 10
    check_val_every_n_epoch: 1

seed: 42

use_neptune: False
neptune:
    api_key: ...
    project: demo